// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANPsOQGf_EM5-J4dwQNqa2aGRh5yA6d6U',
    appId: '1:755496305496:web:9d89d6a349374b1c185b2d',
    messagingSenderId: '755496305496',
    projectId: 'fir-helpdesk-addb4',
    authDomain: 'fir-helpdesk-addb4.firebaseapp.com',
    storageBucket: 'fir-helpdesk-addb4.firebasestorage.app',
    measurementId: 'G-7RTGF3J5W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGZodE6jUmhQVUZbK8FPOxsvTwYbM8d0',
    appId: '1:755496305496:android:c859ba8ac23f46d4185b2d',
    messagingSenderId: '755496305496',
    projectId: 'fir-helpdesk-addb4',
    storageBucket: 'fir-helpdesk-addb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFMU8JvxSNMMhb8dgpQDNVGEs4PYJmAnY',
    appId: '1:755496305496:ios:b4de9bb36f21a97d185b2d',
    messagingSenderId: '755496305496',
    projectId: 'fir-helpdesk-addb4',
    storageBucket: 'fir-helpdesk-addb4.firebasestorage.app',
    iosBundleId: 'com.example.demoHelpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFMU8JvxSNMMhb8dgpQDNVGEs4PYJmAnY',
    appId: '1:755496305496:ios:b4de9bb36f21a97d185b2d',
    messagingSenderId: '755496305496',
    projectId: 'fir-helpdesk-addb4',
    storageBucket: 'fir-helpdesk-addb4.firebasestorage.app',
    iosBundleId: 'com.example.demoHelpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANPsOQGf_EM5-J4dwQNqa2aGRh5yA6d6U',
    appId: '1:755496305496:web:2d4a45e50d1d1361185b2d',
    messagingSenderId: '755496305496',
    projectId: 'fir-helpdesk-addb4',
    authDomain: 'fir-helpdesk-addb4.firebaseapp.com',
    storageBucket: 'fir-helpdesk-addb4.firebasestorage.app',
    measurementId: 'G-F107D4D930',
  );
}
